// <auto-generated />
using System;
using GimnasioAPI.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GimnasioAPI.Migrations
{
    [DbContext(typeof(GimnasioDbContext))]
    partial class GimnasioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GimnasioAPI.MODELS.Planes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Beneficios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Planes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Beneficios = "Puedes acceder a todas las maquinas, actividades del gimnasio",
                            Plan = "Plan Premium",
                            Precio = 39.990000000000002
                        },
                        new
                        {
                            ID = 2,
                            Beneficios = "Tienes los beneficios del plan Premium, más CrossFit y acceso a todas las sucursales",
                            Plan = "Plan Platino",
                            Precio = 59.990000000000002
                        });
                });

            modelBuilder.Entity("GimnasioAPI.MODELS.Sucursal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Dirección")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HoraDeApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraDeCierre")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sucursales");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Dirección = "Centro de Guayaquil",
                            HoraDeApertura = new DateTime(2024, 3, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraDeCierre = new DateTime(2024, 3, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sucursal Centro"
                        },
                        new
                        {
                            ID = 2,
                            Dirección = "Centro Comercial el Dorado",
                            HoraDeApertura = new DateTime(2024, 3, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraDeCierre = new DateTime(2024, 3, 5, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sucursal Centro Comercial el Dorado"
                        });
                });

            modelBuilder.Entity("GimnasioAPI.MODELS.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Apellido = "Pérez",
                            Cedula = "1234567890",
                            Direccion = "Juan Tan Ca Marengo",
                            Nombre = "Juan"
                        },
                        new
                        {
                            ID = 2,
                            Apellido = "González",
                            Cedula = "0987654321",
                            Direccion = "Av. Francisco de Orellana",
                            Nombre = "María"
                        });
                });

            modelBuilder.Entity("GimnasioAPI.MODELS.UsuarioPlanes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("PlanesID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PlanesID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("UsuarioPlanes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            PlanesID = 1,
                            UsuarioID = 1
                        },
                        new
                        {
                            ID = 2,
                            PlanesID = 2,
                            UsuarioID = 2
                        });
                });

            modelBuilder.Entity("GimnasioAPI.MODELS.UsuarioSucursal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("SucursalID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SucursalID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("UsuarioSucursales");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            SucursalID = 1,
                            UsuarioID = 1
                        },
                        new
                        {
                            ID = 2,
                            SucursalID = 2,
                            UsuarioID = 2
                        });
                });

            modelBuilder.Entity("GimnasioAPI.MODELS.UsuarioPlanes", b =>
                {
                    b.HasOne("GimnasioAPI.MODELS.Planes", "Planes")
                        .WithMany()
                        .HasForeignKey("PlanesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GimnasioAPI.MODELS.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planes");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GimnasioAPI.MODELS.UsuarioSucursal", b =>
                {
                    b.HasOne("GimnasioAPI.MODELS.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GimnasioAPI.MODELS.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
